# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.1
xcode_project: SDAnimationChain.xodeproj
xcode_workspace: SDAnimationChain.xcworkspace
xcode_scheme: SDAnimationChain
xcode_sdk: iphonesimulator14.1
env:
  global:
    - FRAMEWORK_NAME=SDAnimationChain
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
 - brew update
 - brew outdated carthage || brew upgrade carthage
# before_script:
#  # bootstrap the dependencies for the project
#  # you can remove if you don't have dependencies
#  - carthage bootstrap
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SDAnimationChain.xcworkspace -scheme SDAnimationChain-Example -sdk iphonesimulator14.1 -destination ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  skip_cleanup: true
  on:
    repo: repo/repo
    tags: true
